### ISSUE TITLE
Too many crates?

### ISSUE THREAD

**Issue by adri326** [klebs6/caffe2-rs#1]
Searching for "neural" or "tensor" on crates.io almost exclusively yields results from this repository, as you have about 250 crates published on crates.io.

This is a bit much, if you'd ask me. It's flooding the search results and making using crates.io's service harder.

The fact that you had to automate generating the READMEs of all these crates using ChatGPT should have been a hint that this wasn't a good project architecture.

I hope you will listen to my concerns and address this issue.

**Comment by klebs6** [comment]
thanks @adri326  for the feedback.  there are a variety of ways to search crates.io for what you are looking for.  if you can provide more specific search terms other than "neural" or "tensor", perhaps you will be able to achieve better results.

The README files are in this project because of their utility and coverage of the material in each crate.  As this codebase evolves, there will be more AI involvement, not less. 

If you are writing code which leverages deep learning, tensor processing, or neural architectures, I suppose you will develop a fine grained understanding of which operators and functions you need in your project.

This crate ecosystem exists to serve the use case of such a user.

**Comment by memchk** [comment]
I happened to run against this when searching for something completely unreleated to AI, DSP code. Have you considered using [crate features](https://doc.rust-lang.org/cargo/reference/features.html)? This is what popular large libraries like tokio do to great effect. You can condition your dependencies and modules on the features so you still get the "pay what you use advantage".

This would allow you to maybe group these operators into families as crates, then you could enable individual operators using the features mechanism.

**Comment by klebs6** [comment]
hi @memchk, this sounds like a great idea 👍 

I think that for the core of this workspace, namely these:
<img width="386" alt="Screen Shot 2023-05-18 at 1 38 23 PM" src="https://github.com/klebs6/caffe2-rs/assets/92199902/02c6ff6d-0e90-43da-9858-15ff5552e1c7">

we should definitely do this. 

Currently, the main bottleneck is actually a program which can effectively translate the function bodies from c++ to rust for each component.

I do have a prototype of this written in `raku`, but there are a few problems with it and I think it needs a rewrite in rust. This way, among other things, we can integrate with `rust-analyzer` and do name resolution, type inference, etc during the transpilation. 

I am currently preparing to write a rust workspace which can do this.  Writing the `raku` prototype gave me a solid understanding of how to translate between the two languages, but I don't think it makes sense to try to scale the raku transpiler anymore.  

Once the raku transpiler reached a certain size, its development cycle slowed down rather significantly.  I think Rust will be much better at the scale necessary to solve the problem.

Anyway, I am happy to take a PR for the functionality you mentioned above if you'd like to help out.  I'll probably be able to do it myself later on, but plan to focus on bringing up the transpiler first.  This is where the main bottleneck is.

**Comment by klebs6** [comment]
possibly closed -- see #3 and #4
